- name: Demo on fileVars 
  hosts: all                                # host group name 
  vars:                                     # Play level variables
    URL: "play.google.com"         
  vars_files:
    - "vars-dev.yaml"
    - "vars-prod.yaml"
  tasks:
    - name: Printing play variable
      ansible.builtin.debug:
        msg: "Value of the url {{ URL }}"
      
    - name: Printing variables from file
      ansible.builtin.debug:
        #msg: "Current Environment is {{ ENV }} and the dev-lead name is {{ DEVLEAD }} their value is {{ A }}"
        msg: "lead person name is {{ DEVLEAD }} and their value is {{ A }}"